version: '3'
services:
  service1:
    build:
      context: ./service1
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  service2:
    build:
      context: ./service2
      dockerfile: Dockerfile
    ports:
      - 5001:5001
  service3:
    build:
      context: ./service3
      dockerfile: Dockerfile
    ports:
      - 5002:5002
